lib/trollop.rb

For older Rubies without io/console, fallback to shelling out to tputs.
Related to #29 and #33

Remove curses in favor of io/console

---

lib/trollop.rb
test/test_trollop.rb

Currently, it is simply forbidding to have an empty array as a default.  This is because trollop attempts to first derive the default, and then to compare that to the given type, and it is not possible to know the type of an empty array.
If the type is in fact given, however, there is no problem, so long as the type is a MULT_ARGS_TYPE.
(This is how I prefer my pull requests to look)

Allow empty array default 2

---

.travis.yml
Gemfile.travis

Have a gemfile for travis that works with 1.8
When Gemnasium parses `Gemfile` via regular expressions. So it is ignoring the `if` which is only used in ruby 1.8.
This PR introduces a travis specific Gemfile that lets travis install the proper gems for 1.8, but does not confuse Gemnasium.

travis specific gemfile

---

lib/trollop.rb
test/test_trollop.rb

When a default is an array, and the user specifies a flag with no params
proceed as if all defaults were stated
Fixes #38 
@Fryguy Debating between this and just stating that #11 should be redacted

Followup to default parameters with no values.

---

test/test_trollop.rb

This PR removes 2 lines from test that are not needed.
Aside but probably more significant:
~~For some reason~~ `test_trollop.rb` is showing up in test coverage but not `trollop.rb`. **ANSWER:** because it is being included in the `gemspec`.
~~@Fryguy ideas around this?~~
**EDIT**: reworded issue

remove unneeded statements from test

---

test/test_trollop.rb

too much trash in test output.
bunch of "Options: ..."
Also ensure that the system is exiting with an error status for errors and not for help.
/cc @Fryguy

Hide verbose output

---

Gemfile.travis
Rakefile
lib/trollop.rb
test/support/assert_helpers.rb
test/test_helper.rb
test/test_trollop.rb
test/trollop/parser_test.rb
trollop.gemspec

I want more confidence in the tests (so I can refactor).
- move test files so we can split them out
- upgrade minitest
- don't `include "trollop"` in `Gemfile` that is producing a false 100% coverage

Splitup tests

---

.travis.yml

Having some trouble with travis and ruby-head.
It is failing to build `unf_ext`. (Think this is a coveralls dependency?)
Marking ruby-head as ok to fail.
@Fryguy Thoughts

allow failures with ruby-head

---

lib/trollop.rb
test/trollop_test.rb

Not thrilled about changing `CommandLineError`, but seemed the best option
Fixes #57 
/cc @Fryguy @jaredbeck

add ability to give errors custom exit codes

---

lib/trollop.rb
test/trollop/command_line_error_test.rb
test/trollop/help_needed_test.rb
test/trollop/parser_test.rb
test/trollop/version_needed_test.rb
test/trollop_test.rb

refactored `usage` incorrectly. put it back
Add specs around the getter/setters for educate

properly display usage

---

test/trollop/parser_educate_test.rb
test/trollop/parser_opt_test.rb
test/trollop/parser_parse_test.rb
test/trollop/parser_test.rb
test/trollop_test.rb

Pull out the parser tests from the main trollop test suite
misc:
- moved renamed test names: educate/help

Test parser

---

.travis.yml

It's not clear if there was a reason to exclude these rubies... either way, I thought it was worth a try to see if we wanted to add them to the matrix.
I assume since we support 1.8.7 in travis, we probably should be testing 1.9.2.

Add 1.9.2/2.0/2.1 to travis test matrix.

---

README.md
lib/trollop.rb

Similar to issue #47, there was still a reference to the Ruby license in the header of the lib/trollop.rb file which is amended here. In addition to this, the Markdown linking to the MIT license in the README.md file was broken; this is also fixed here, but isolated to its own commit.
Thank you!

Refer to the MIT license consistently

---

lib/trollop.rb

on the command line don't add `(default: )` when the `default` is the
blank string ( `""`)

Don't display default when it is blank

---

lib/trollop.rb

travis returns a 0 for width.
This is causing odd wrapping issues and failing tests.
Now, we're defaulting to 80

better unix support for multi line comments

---

lib/trollop.rb
test/trollop/parser_test.rb

@Fryguy this is just the beginning
Want to move each parameter option into its own class.
In the longer term, most of the case statements will be converted to inheritance / ducktyping.
downside:
some constants in the documented public interface will go away (e.g.: `FLOAT_RE`, `MULTI_ARG_TYPES`). Not sure if semver says this is a major or minor update.
I really don't think anyone should be accessing those constants.
I'm debating many PRs. Or a single PR. (single PR is nice to get a feel for the final product)

Option class

---

lib/trollop.rb
test/trollop/parser_test.rb

The current implementation of ignore_invalid_options does not include the ignored options in the `leftovers` and does not correctly `stop_on_unknown`. This is a consequence of zero being truthy in Ruby (in `unless num_params_taken`) and an off-by-one error in the code for handling that case. This PR fixes `ignore_invalid_options` and adds a test suite for it.

Fix the behavior of ignore_invalid_options

---

lib/trollop.rb
test/trollop_test.rb

Allow die to support 2 or 3 parameters
Follow up to #57 and #63 
@jaredbeck Does this work per our discussion?

Trollop.die now supports message, exit_code

---

lib/trollop.rb

This is a follow-on to @kbrock 's PR #93 
Rebased to manageiq/trollop/master and applied as minimal a change set as I could to implement the subclassing.  I thought I had rebased this properly before, but was quite mistaken.  
The "registry" still exists as a fixed hash (and currently without any user accessible functions) so that it can dispatch to the proper subclass.
The outward facing API changes were as minimal as possible.  I dont have a solution to the flag issue yet, perhaps we could just check `opt.is_a? BooleanOption`

Refactoring options, adding Option subclasses.

---

test/optimist/parser_test.rb

There were warnings when running `rake`.
This fixes them.
The warnings:
1) `DEPRECATED: Use assert_nil if expecting nil`
2) `warning: method redefined; discarding old test_integer_formatting` and `warning: previous definition of test_integer_formatting was here`
The fixes:
* 1 was fixed by using the suggested `assert_nil`
* 2 was fixed by suffixing the duplicate test with `"_default"`

Fix test warnings

---

.travis.yml

In the previous commit 5a61393b14c1a9ef4db0b332f730e5167b1585dc
`manageiq-style` has been introduced.
https://github.com/okuramasafumi/optimist/blob/master/optimist.gemspec#L33
This gem includes `rubocop` which doesn't work with Ruby 2.2 and 2.3.
In the error log of TravisCI, it says:
```
manageiq-style was resolved to 1.1.3, which depends on
rubocop (~> 0.82.0) was resolved to 0.82.0, which depends on
ruby (>= 2.4.0)
```
I believe we should drop support for older Rubies such as 2.2 and 2.3,
because using RuboCop means we cannot use Ruby 2.3 and older, and
Ruby 2.3 is so old and not supported anymore (EOL).

Remove `2.2` and `2.3` from CI matrix

---

test/optimist/parser_test.rb

Adds tests for the following cases:
- Short flags for boolean cases
- Long opt names with dashes

Add some tests cases to ParserTest

---

.github/workflows/ci.yml
optimist.gemspec

This PR moves CI to GitHub Actions
In addition to setting up a basic configuration that includes those Rubies previously tested by Travis this PR:
1. Adds jruby-9.3 and Ruby 3.1 to the CI matrix
2. Loosens the Rake requirement in the gemspec to allow a Rake version that's compatible with ruby-head

Migrate to GitHub Actions

---

test/optimist/command_line_error_test.rb
test/optimist/help_needed_test.rb
test/optimist/parser_educate_test.rb
test/optimist/parser_opt_test.rb
test/optimist/parser_parse_test.rb
test/optimist/parser_test.rb
test/optimist/version_needed_test.rb
test/optimist_test.rb

Current style has long been to use Minitest instead of MiniTest at least for 3 years, and with minitest 5.19, MiniTest usage support is hidden unless explicitly setting ENV["MT_COMPAT"].
https://github.com/minitest/minitest/commit/a2c6c18570f6f0a1bf6af70fe3b6d9599a13fdd6
Switch to use Minitest style.

Test: use recent Minitest style

---

.github/workflows/ci.yaml

Ruby 3.3 has [been released](https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/)! Let's add it to the CI build matrix for confidence in compatibility.

CI: add Ruby 3.3 to the test matrix

---

lib/optimist.rb
test/optimist/parser_test.rb

This makes displaying a mixed set of parameters cleaner and easier to understand. This is in line with the behavior of common GNU tools such as rsync.
Old way:
```
Options:
-i, --init        Creates a skeleton config file in the current working directory
-v, --verbose     Enables verbose output. Twice will enable very-verbose output (good for logging)
-y, --yes         Assume 'yes' to all questions for headless execution
--yaml=<s>        Specify a yaml file to load
-h, --help        Show this message
```
New way:
```
Options:
-i, --init        Creates a skeleton config file in the current working directory
-v, --verbose     Enables verbose output. Twice will enable very-verbose output (good for logging)
-y, --yes         Assume 'yes' to all questions for headless execution
--yaml=<s> …
```

Align the short and long forms into their own columns in the help output

---

lib/optimist.rb

Changes a dead link to rubyforge.org and points to the equivalent documentation that exists today.
@miq-bot add-label documentation

rubyforge.org is dead, changing documentation pointer

---

examples/didyoumean.rb
lib/optimist.rb
test/optimist/parser_test.rb

Enables "did_you_mean" style suggestions for long options.
This works similar to how it does when you misspell something in Ruby, but applied to long options in Optimist.
It uses the same string-distance algorithm as Ruby to see if any of the long options are within a reasonable distance.  The `DidYouMean` feature was added in ruby2.3, so this will not work with older rubies but I dont believe we support those anymore.
There is a keyword option that can be passed in at the Optimist.options() level to disable suggestions, e.g.
`Optimist.options(ARGV, suggestions: false)` and get legacy behavior.  Some tweaks to how options are merged was necessary for this.
examples script and output provided in the `/examples` directory.
@miq-bot add-label enhancement

adding support for DidYouMean when long options are spelled incorrectly

---

lib/optimist.rb

Enabling `frozen string literal: true`
This in preparation for ruby 3.4 behavior:
[String](https://docs.ruby-lang.org/en/master/String.html) literals in files without a frozen_string_literal comment now behave as if they were frozen.
per https://docs.ruby-lang.org/en/master/NEWS_md.html

Enable frozen_string_literal for future-ruby support

---

lib/optimist.rb
test/optimist/parser_educate_test.rb
test/optimist/parser_test.rb

Using `permitted:` when defining an option restricts the allowed values that a end-user inputs to a pre-defined list.
__Note__: This is a continuation of an old PR which I accidentally closed by deleting my old fork (it was too old to use now). [This is the PR](https://github.com/ManageIQ/optimist/pull/97). It is now rebased as requested, and I have added the tests, but I never got a final answer if you wanted it merged in this form or if you wanted to do something else. I've been using my own fork for the last few years and so far I haven't hit any issues with the code as written.
Defining an option like this...
```ruby
opt :name, type: strings, permitted: ['Jack', 'Jill']
```
...restricts the input to one of the following:
```shell
$ mycmd -n Jack
$ mycmd -n Jill
$ mycmd -n Jack Jill …
```

Using permitted: restricts the allowed values that a end-user inputs to a pre-defined list

---

lib/optimist.rb

Merge of did-you-mean branch and frozen-string literal branch caused this issue, as the DYM branch did not fully abide by frozen-string literal rules.
Funny enough, behavior of the frozen-string-literal comment is different on rb2.7 and 3.x
Fixes fails mentioned #152 
@miq-bot add-label bug

fixes frozen string issue on old rb2.7, removed useless code

---

.github/workflows/ci.yaml

Temporarily allow failures for ruby-head until we can understand why it fails.

Allow failures for ruby-head

---

lib/optimist.rb
test/optimist/parser_test.rb
test/support/assert_helpers.rb

Add support for inexact long-option matches, inspired by Perl's Getopt::Long.
Allows the user to provide a leading substring of characters for a long-option so long as it is not ambiguous which option it references
E.g. if you have options `cake` and `carrot`, 
+ :heavy_check_mark: `--car`, `--carr`, `--carro`, `--carrot` can enable `carrot`
+ :heavy_check_mark: `--cak`, `--cake` can enable `cake`
+ :x: `--ca` is invalid because it is ambiguous.
The behavior is not enabled for `--no` options due to concerns over confusion.
The exact_match behavior is defaulted to true, but can be turned off by passing in settings. `exact_match: false`
Additional tests were added to clarify behavior around the settings hash.
@miq-bot add-label enhancement

Add exact_match to settings, defaulting to inexact matching

---

lib/optimist.rb
test/optimist/parser_test.rb

In Optimist short options are automatically created for any given long option. (e.g: `-f` for `--file`)
Once enough options exist you are likely to have short-option name collisions, whereby you may compete for the short-option, and optimist must choose a backup short-letter e.g. 
```ruby
opt :file, "a filename", type: String
opt :format, "file format", type: String
```
Optimist wont allow collisions and thus it will go through letters to try to find a different unused letter.  In this case `-f` for `--file` and `-o` for `--format` (because the `f` was already used).  Unfortunately this makes the order of `opt` important.  If you do this:
```ruby
opt :format, "file format", type: String
opt :file, "a filename", type: String
```
then in this case you get `-f` for `--format` and `-i` for …

added settings to only create short options explicitly

---

examples/alt_names.rb
lib/optimist.rb
test/optimist/alt_names_test.rb
test/optimist/parser_test.rb

It can be useful to have more than one option name for the same option.  E.g. you may have a `--concat` option, but intuitively to some users they would rather `--append`.  Or sometimes you want to change names of the option but keep backward compatibility.
This enables short options and long options to have more than one name.
For short options, the `chars:` can now take a list of strings/symbols (previously was just a symbol or char)
For long options, the `alt:` takes additional alternate long options.  The value provided in `long:` is still respected, any name(s) given in `alt:` are used in addition to the default long-argument or what was provided in `long:`
There was some refactoring of how short and long options work, which pushed them down into a `ShortNames` and `LongNames` class. …

Add alt longname and multiple char support

---

examples/constraints.rb
lib/optimist.rb
test/optimist/parser_constraint_test.rb
test/optimist/parser_test.rb

+ Refactor constraints (depends/conflicts/either) into separate classes (`DependConstraint`, `ConflictConstraint`, `EitherConstraint`) with an abstract `Constraint` class.
+ ~Add `validate` method which points to new `MinMaxConstraint`, plus tests.~
+ ~tbh i'm not too sure about the `validate` name, the name feels a little unclear about its purpose to me.~
@miq-bot add-label refactoring

Refactor constraints

---

lib/optimist.rb
test/optimist/parser_permitted_test.rb

Fixes permitted range comparison issue.  Previously the range would be turned into an array which could blow up memory.
Adds more tests for permitted behavior.
@miq-bot add-label enhancement test

enhancements to permitted option

---

lib/optimist.rb
test/optimist/alt_names_test.rb
test/optimist/parser_constraint_test.rb
test/optimist/parser_parse_test.rb
test/optimist/parser_permitted_test.rb
test/optimist/parser_test.rb
test/optimist_test.rb

Convert `assert_raises` to `assert_raises_errmatch` for all cases where practical.  Add error checking Regexps where ones did not previously exist.
Fixed a bug caused in #151 in how some messages were printed which was not obvious until expectations were written for the output messages
Fixes #157 
@miq-bot add-label test

Fix assert_raises to assert_raises_errmatch

---

examples/a_basic_example.rb
examples/banners1.rb
examples/banners2.rb
examples/banners3.rb
examples/medium_example.rb
examples/partialmatch.rb
examples/permitted.rb
examples/types_custom.rb

>> Describe what this Pull Request does and why you think it is needed.
Added some new examples, new users might find them helpful or get some ideas on how to use Optimist.  They could also look at the tests, but examples are more approachable for most people.
@miq-bot add-label documentation

Adding some examples

---

.github/workflows/ci.yaml
optimist.gemspec

Add Ruby 3.4 support

---

examples/boolean.rb
lib/optimist.rb
test/optimist/parser_educate_test.rb

Fixes #178
@kbrock Please review.

Fix issue where negative boolean flags were output incorrectly

---

test/optimist/alt_names_test.rb
test/optimist/parser_educate_test.rb
test/optimist/parser_test.rb
test/support/assert_helpers.rb

These tests are passing in a default value to StringIO, which is unnecessary (and in the case of the "w" is incorrect). That default value is a frozen string literal, which StringIO will later modify, leading to an error. Since they aren't needed we can remove them.
@kbrock Please review.

Fix issues with frozen strings which fail jruby-head
